version: '3.3'
services:
  data:
    image: tianon/sleeping-beauty
    volumes:
      - data:/var/lib/postgresql/data
      - data:/data

  db:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - "5432:5432"

  app:
    build:
      context: ./dockerfiles/phoenix
      args:
        - ELIXIR_VERSION=${ELIXIR_VERSION}
        - PHOENIX_VERSION=${PHOENIX_VERSION}
        - PHOENIX_APP_NAME=${PHOENIX_APP_NAME}
        - WORKDIR=${WORKDIR}
    volumes:
      - "${APPLICATION}:${WORKDIR}${PHOENIX_APP_NAME}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOSTNAME=${POSTGRES_HOSTNAME}
    command: mix phoenix.server
    ports:
      - "4000:4000"
    links:
      - db:db

  # redis:
  #   image: redis:latest
  #   volumes:
  #     - data:/data

volumes:
  data:
